# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DEPLOYMENT_URL: ${{ vars.DEPLOYMENT_URL }}
        name: Rebuild on App Platform
        # error if we do not get a JSON response containing the new deployment
        run: |
          echo "$DEPLOYMENT_URL"
          [ -z "$TOKEN" ] && echo "No token"
          curl \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            "$DEPLOYMENT_URL" -XPOST -d '{"force_build": true}' \
            | grep '{"deployment":'
